<a href="https://colab.research.google.com/github/AiHuzaifa/titanic-survival-prediction/blob/main/Titanic_Data_Set(Logistic_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
import numpy as np

In [56]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train (2).csv

In [57]:
from google.colab import files

uploaded = files.upload()

Saving test.csv to test (2).csv

In [58]:
from google.colab import files

uploaded = files.upload()

Saving gender_submission.csv to gender_submission (2).csv

In [59]:
de_test = pd.read_csv("test.csv")
de_test["Sex"] = de_test["Sex"].map({"male": 0, "female": 1})
y_test = pd.read_csv("gender_submission.csv")
x_test = de_test[["Age", "Fare", "Pclass","Sex"]]
x_test["Age"] = x_test["Age"].fillna(x_test["Age"].median())
Y_test = y_test["Survived"]

/tmp/ipykernel_1192/287805352.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test["Age"] = x_test["Age"].fillna(x_test["Age"].median())

In [60]:
df = pd.read_csv("train.csv")

In [61]:
df = pd.read_csv("train.csv")

In [62]:
df.shape

(891, 12)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [64]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [65]:
df["Sex"] = df["Sex"].map({"male": 0, "female": 1})
df["Age"] = df["Age"].fillna(df["Age"].median())
X = df[["Age", "Fare", "Pclass","Sex"]]
y = df["Survived"]

In [66]:
X.isnull().sum()

Age       0
Fare      0
Pclass    0
Sex       0
dtype: int64

In [67]:
X.isnull().sum()

Age       0
Fare      0
Pclass    0
Sex       0
dtype: int64

In [68]:
print("X:", X.shape)

print("y:", y.shape)

X: (891, 4)
y: (891,)

In [69]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X)
X_test = scaler.transform(x_test)

In [70]:
class Logistic_Regression:
  def __init__(self, lr = 0.01,n_iter = 6000):
    self.lr = lr
    self.n_iter = n_iter
    self.weights = None
    self.base = None

  def sigmoid(self,z):
    return 1/(1+(np.exp(-z)))

  def fit(self,X_train,y_train):
    self.weights = np.zeros(X_train.shape[1])
    self.base = 0
    m = X_train.shape[0]

    for _ in range(1000):
      y_h = np.dot(X_train,self.weights) + self.base
      sig = self.sigmoid(y_h)

      cost = -(y_train*np.log(sig)+(1-(y_train))*np.log(1-sig)).mean()
      if _ % 100 == 0:
        print(cost)

      dw = (X_train.T @ (sig - y_train))/m
      db = (sig-y_train).mean()

      self.weights = self.weights - self.lr*dw
      self.base = self.base - self.lr*db
      if _ % 99 ==0:
        print(self.weights)
        print(self.base)

  def predict(self,x_test):
    y_h = np.dot(x_test,self.weights) + self.base
    return self.sigmoid(y_h)

  def accuracy(self, y_true, y_pred_prob):
    y_pred = np.where(y_pred_prob >= 0.5, 1, 0)
    return np.mean(y_true == y_pred)

In [71]:
lg = Logistic_Regression()
lg.fit(X_train,y)

0.6931471805599453
[-0.00031567  0.00125133 -0.0016461   0.00264242]
-0.0011616161616161617
[-0.0325366   0.09760736 -0.13713129  0.22965358]
-0.10291916672254053
0.599718668703601
[-0.06421564  0.15566905 -0.23310775  0.40231065]
-0.1827419233993147
0.5487895678800812
[-0.09353425  0.19158778 -0.30509717  0.53674526]
-0.24621109383549555
0.5188543285536495
[-0.12003254  0.21397853 -0.36198184  0.64358041]
-0.2975607482752147
0.5001358114707124
[-0.14378932  0.22761622 -0.40886919  0.72988433]
-0.3398095940780702
0.48784747584897503
[-0.16506667  0.23532708 -0.44880231  0.80052392]
-0.37508866594249934
0.479457671643858
[-0.18416624  0.23888486 -0.48366838  0.85896591]
-0.4049210367417771
0.47353887457172955
[-0.20137446  0.23945876 -0.51468418  0.90775234]
-0.43041699335840866
0.46924380182235503
[-0.21694447  0.23785195 -0.54266374  0.94879248]
-0.45240327994140894
0.46604838487310624
[-0.23109302  0.23463566 -0.56817098  0.9835489 ]
-0.4715081884680678

In [72]:
y_pred_prob = lg.predict(X_test)
acc = lg.accuracy(Y_test, y_pred_prob)
print(f"Test Accuracy: {acc * 100:.2f}%")

Test Accuracy: 97.13%